### ISSUE TITLE
Classes can't be injected due to EmbeddableWidget decorator

### ISSUE THREAD

**Issue by KyorCode** [digipolisantwerp/embeddable-widgets_component_angular#3]
Classes decorated with the EmbeddableWidget decorator don't receive their injected services/classes.

`javascript
@Component({
  templateUrl: './form-renderer.page.html'
})
@EmbeddableWidget('definitions/form-renderer.json')
export class FormRendererPage {
  constructor(private ngZone: NgZone) {
  }

  schema: FormSpec;
  form: FrForm;
  step = 1;
  autoStep = true;
...
`

ngZone will be `undefined`. In this case I needed NgZone to make the renderer update after performing a callback outside of angular context.

**Comment by jsebrech** [comment]
Fixed in 1.0.2

**Comment by KyorCode** [comment]
@jsebrech Fix doesn't work for constructors that don't inject anything.
https://github.com/digipolisantwerp/embeddable-widgets_component_angular/blob/master/src/widget.decorator.ts#L45 could be null which causes line 47 to crash.

**Comment by jsebrech** [comment]
fixed remaining issue in `1.0.3`
